// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0dCf1OF9xzzDGAWZZvwWH1z_6BQdENs',
    appId: '1:450065290583:web:2f9e344e088d3378951a12',
    messagingSenderId: '450065290583',
    projectId: 'm-chat-app-b',
    authDomain: 'm-chat-app-b.firebaseapp.com',
    storageBucket: 'm-chat-app-b.appspot.com',
    measurementId: 'G-NKCD1LL2MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gH2Rho91JzSY7bGxzZmc2IpMAcsJmPE',
    appId: '1:450065290583:android:d262af6a0a7a6722951a12',
    messagingSenderId: '450065290583',
    projectId: 'm-chat-app-b',
    storageBucket: 'm-chat-app-b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQrzO-XT64ztXDIp4RakXtpzY9haYYpg',
    appId: '1:450065290583:ios:d83181728e577444951a12',
    messagingSenderId: '450065290583',
    projectId: 'm-chat-app-b',
    storageBucket: 'm-chat-app-b.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBQrzO-XT64ztXDIp4RakXtpzY9haYYpg',
    appId: '1:450065290583:ios:d83181728e577444951a12',
    messagingSenderId: '450065290583',
    projectId: 'm-chat-app-b',
    storageBucket: 'm-chat-app-b.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo0dCf1OF9xzzDGAWZZvwWH1z_6BQdENs',
    appId: '1:450065290583:web:f08164d88366bbcc951a12',
    messagingSenderId: '450065290583',
    projectId: 'm-chat-app-b',
    authDomain: 'm-chat-app-b.firebaseapp.com',
    storageBucket: 'm-chat-app-b.appspot.com',
    measurementId: 'G-0VV0NL74ZK',
  );
}
