// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYzC-0dxmwTmYXHVSSEqlgzqktaf2CJbM',
    appId: '1:278766714779:web:de1467cceca2c2f770eb3e',
    messagingSenderId: '278766714779',
    projectId: 'f-chat-app-b',
    authDomain: 'f-chat-app-b.firebaseapp.com',
    storageBucket: 'f-chat-app-b.appspot.com',
    measurementId: 'G-WVCKGSMHTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9d8a_HdDYw8A-2dt23hhM18hNq82Q8s',
    appId: '1:278766714779:android:ebee5aeec4050c5e70eb3e',
    messagingSenderId: '278766714779',
    projectId: 'f-chat-app-b',
    storageBucket: 'f-chat-app-b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWo5dN-Aehea_lcWEyun_FfYNtbMqT3Y',
    appId: '1:278766714779:ios:4aa747a39dd331e870eb3e',
    messagingSenderId: '278766714779',
    projectId: 'f-chat-app-b',
    storageBucket: 'f-chat-app-b.appspot.com',
    iosBundleId: 'com.example.fbChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWo5dN-Aehea_lcWEyun_FfYNtbMqT3Y',
    appId: '1:278766714779:ios:4aa747a39dd331e870eb3e',
    messagingSenderId: '278766714779',
    projectId: 'f-chat-app-b',
    storageBucket: 'f-chat-app-b.appspot.com',
    iosBundleId: 'com.example.fbChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYzC-0dxmwTmYXHVSSEqlgzqktaf2CJbM',
    appId: '1:278766714779:web:66a56c09ccd7490770eb3e',
    messagingSenderId: '278766714779',
    projectId: 'f-chat-app-b',
    authDomain: 'f-chat-app-b.firebaseapp.com',
    storageBucket: 'f-chat-app-b.appspot.com',
    measurementId: 'G-5ZNLGLSW7B',
  );
}
